Add testID props to Text & TextInput components
callstackincubator/bs-react-native-paper pull request #74
Opened 2019-01-28 10:15 UTC by DCKT

The props `testID` should be allowed for this component following the  react native [TextInput](https://facebook.github.io/react-native/docs/textinput#props) & ([Text](https://facebook.github.io/react-native/docs/text#testid)) api.

### Motivation
Use `testID` props for e2e testing

### Test plan

2019-01-28 11:35 UTC, medson10 requested changes

2019-01-28 11:35 UTC, medson10 commented on re/Paper_Text.re
> +        "testID": fromOption(testID),
Hi thanks for your contribution, looks like you removed the style prop here, can you add again?

2019-01-28 12:47 UTC, Trancever requested changes

2019-01-28 12:47 UTC, Trancever commented on re/Paper_Text.re
> +        "testID": fromOption(testID),
Hi, we can merge it when you add back the style prop.

2019-01-28 13:26 UTC, DCKT commented on re/Paper_Text.re
> +        "testID": fromOption(testID),
oops fixed sorry !

2019-01-28 14:59 UTC, medson10 approved these changes

2019-02-03 15:12 UTC, Trancever approved these changes

2019-02-03 15:12 UTC, merged